"""program_prices

Revision ID: 0abd2055f2d1
Revises: cf9014709856
Create Date: 2024-12-24 08:55:28.641153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0abd2055f2d1'
down_revision: Union[str, None] = 'cf9014709856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_items',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_prices',
    sa.Column('name', sa.Enum('FT', 'WC', 'CM', 'ID', name='programpricecategory'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('client_document_client_id_key', 'client_document', type_='unique')
    op.create_unique_constraint(None, 'client_document', ['client_id', 'series', 'number'])
    op.add_column('expenses', sa.Column('caregory_id', sa.Integer(), nullable=True))
    op.drop_constraint('expenses_category_amount_employee_id_key', 'expenses', type_='unique')
    op.create_unique_constraint(None, 'expenses', ['caregory_id', 'amount', 'employee_id'])
    op.create_foreign_key(None, 'expenses', 'cost_items', ['caregory_id'], ['id'])
    op.drop_column('expenses', 'category')
    op.add_column('program_client_room', sa.Column('entry_date', sa.Date(), nullable=False))
    op.drop_column('program_client_room', 'enty_date')
    op.drop_column('programs', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('program_client_room', sa.Column('enty_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('program_client_room', 'entry_date')
    op.add_column('expenses', sa.Column('category', postgresql.ENUM('AC', 'TR', 'FD', 'SR', name='expensecategory'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='unique')
    op.create_unique_constraint('expenses_category_amount_employee_id_key', 'expenses', ['category', 'amount', 'employee_id'])
    op.drop_column('expenses', 'caregory_id')
    op.drop_constraint(None, 'client_document', type_='unique')
    op.create_unique_constraint('client_document_client_id_key', 'client_document', ['client_id'])
    op.drop_table('program_prices')
    op.drop_table('cost_items')
    # ### end Alembic commands ###
