"""expense category field

Revision ID: 27e2e2250f4c
Revises: 0abd2055f2d1
Create Date: 2024-12-25 20:57:38.900657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e2e2250f4c'
down_revision: Union[str, None] = '0abd2055f2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_document_client_id_fkey', 'client_document', type_='foreignkey')
    op.create_foreign_key(None, 'client_document', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('client_profile_client_id_fkey', 'client_profile', type_='foreignkey')
    op.create_foreign_key(None, 'client_profile', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('expenses', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('expenses_caregory_id_amount_employee_id_key', 'expenses', type_='unique')
    op.create_unique_constraint(None, 'expenses', ['category_id', 'amount', 'employee_id'])
    op.drop_constraint('expenses_caregory_id_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'cost_items', ['category_id'], ['id'])
    op.drop_column('expenses', 'caregory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('caregory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_caregory_id_fkey', 'expenses', 'cost_items', ['caregory_id'], ['id'])
    op.drop_constraint(None, 'expenses', type_='unique')
    op.create_unique_constraint('expenses_caregory_id_amount_employee_id_key', 'expenses', ['caregory_id', 'amount', 'employee_id'])
    op.alter_column('expenses', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('expenses', 'category_id')
    op.drop_constraint(None, 'client_profile', type_='foreignkey')
    op.create_foreign_key('client_profile_client_id_fkey', 'client_profile', 'client', ['client_id'], ['id'])
    op.drop_constraint(None, 'client_document', type_='foreignkey')
    op.create_foreign_key('client_document_client_id_fkey', 'client_document', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
