"""first

Revision ID: 373ca5853d12
Revises: 
Create Date: 2024-11-29 21:54:03.627129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373ca5853d12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('client_indx', 'client', ['last_name', 'name'], unique=False)
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_table('hotel',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('contacts', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_email'), 'hotel', ['email'], unique=True)
    op.create_index(op.f('ix_hotel_title'), 'hotel', ['title'], unique=False)
    op.create_table('program',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AC', 'CL', name='programstatus'), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_program_title'), 'program', ['title'], unique=False)
    op.create_table('client_document',
    sa.Column('doc_type', sa.Enum('PS', 'CT', name='clientdocumenttype'), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('date_of_issue', sa.Date(), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('client_profile',
    sa.Column('shirt_size', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NW', 'RG', name='clientstatus'), nullable=False),
    sa.Column('nutrition_features', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('hotel_rooms',
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('room_price', sa.Integer(), nullable=False),
    sa.Column('room_volume', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NC', 'AC', 'PF', name='clientprogramstatus'), nullable=False),
    sa.Column('contract_status', sa.Enum('NS', 'SD', 'SG', name='clientporgramcontractstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'client_id')
    )
    op.create_table('client_Program_payment',
    sa.Column('client_program_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_program_id'], ['program_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_family',
    sa.Column('client_relation', sa.Enum('HB', 'WF', 'CD', 'FD', name='clientfamilyrelation'), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['client_document.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['client_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'document_id')
    )
    op.create_table('program_rooms',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['hotel_rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'hotel_id', 'room_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_rooms')
    op.drop_table('client_family')
    op.drop_table('client_Program_payment')
    op.drop_table('program_clients')
    op.drop_table('hotel_rooms')
    op.drop_table('client_profile')
    op.drop_table('client_document')
    op.drop_index(op.f('ix_program_title'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_hotel_title'), table_name='hotel')
    op.drop_index(op.f('ix_hotel_email'), table_name='hotel')
    op.drop_table('hotel')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_index('client_indx', table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
