"""partner service type

Revision ID: 55a36a33d334
Revises: d2bd8f26a876
Create Date: 2025-04-17 15:54:26.649493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a36a33d334'
down_revision: Union[str, None] = 'd2bd8f26a876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_services', sa.Column('service_type', sa.Enum('GR', 'CL', name='expensetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_services', 'service_type')
    # ### end Alembic commands ###
