"""program prices

Revision ID: 5da8a85584ef
Revises: 55a36a33d334
Create Date: 2025-04-18 13:48:19.080349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5da8a85584ef'
down_revision: Union[str, None] = '55a36a33d334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_prices', sa.Column('base_price', sa.Integer(), nullable=False))
    op.add_column('program_prices', sa.Column('loayal_price', sa.Integer(), nullable=False))
    op.add_column('program_prices', sa.Column('comunity_price', sa.Integer(), nullable=False))
    op.drop_column('program_prices', 'name')
    op.drop_column('program_prices', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_prices', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('program_prices', sa.Column('name', postgresql.ENUM('FT', 'WC', 'CM', 'ID', name='programpricecategory'), autoincrement=False, nullable=False))
    op.drop_column('program_prices', 'comunity_price')
    op.drop_column('program_prices', 'loayal_price')
    op.drop_column('program_prices', 'base_price')
    # ### end Alembic commands ###
