"""partners db row

Revision ID: 7a3840d05fc0
Revises: fe9be091ceda
Create Date: 2025-03-07 15:09:00.528172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3840d05fc0'
down_revision: Union[str, None] = 'fe9be091ceda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('law_title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('EX', 'TF', 'OT', name='partnercategory'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bic', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('cor_account', sa.String(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    op.drop_table('partners')
    # ### end Alembic commands ###
