"""partner service

Revision ID: 8482f69effb6
Revises: 7a3840d05fc0
Create Date: 2025-03-15 19:51:41.584668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8482f69effb6'
down_revision: Union[str, None] = '7a3840d05fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_services',
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('partners', 'service_name')
    op.drop_column('partners', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('partners', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('partner_services')
    # ### end Alembic commands ###
