"""program room sharing

Revision ID: a41d2b37b62a
Revises: 5da8a85584ef
Create Date: 2025-04-22 14:38:54.417113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41d2b37b62a'
down_revision: Union[str, None] = '5da8a85584ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_client_room', sa.Column('no_sharing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_client_room', 'no_sharing')
    # ### end Alembic commands ###
