"""client profile nullable fields

Revision ID: e914048cbefb
Revises: 8482f69effb6
Create Date: 2025-03-22 22:05:49.026851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e914048cbefb'
down_revision: Union[str, None] = '8482f69effb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_profile', 'shirt_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('client_profile', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('client_profile', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_profile', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('client_profile', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('client_profile', 'shirt_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
