"""staff comment

Revision ID: fe9be091ceda
Revises: e1773120b14b
Create Date: 2025-02-24 17:06:43.356356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9be091ceda'
down_revision: Union[str, None] = 'e1773120b14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('program_client_room', sa.Column('program_room_id', sa.Integer(), nullable=False))
    op.drop_constraint('program_client_room_program_client_id_room_id_key', 'program_client_room', type_='unique')
    op.create_unique_constraint(None, 'program_client_room', ['program_client_id', 'program_room_id'])
    op.drop_constraint('program_client_room_room_id_fkey', 'program_client_room', type_='foreignkey')
    op.create_foreign_key(None, 'program_client_room', 'program_rooms', ['program_room_id'], ['id'])
    op.drop_column('program_client_room', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_client_room', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'program_client_room', type_='foreignkey')
    op.create_foreign_key('program_client_room_room_id_fkey', 'program_client_room', 'hotel_rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'program_client_room', type_='unique')
    op.create_unique_constraint('program_client_room_program_client_id_room_id_key', 'program_client_room', ['program_client_id', 'room_id'])
    op.drop_column('program_client_room', 'program_room_id')
    op.drop_column('employees', 'comment')
    # ### end Alembic commands ###
